spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.210.38.19/transaction_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gragon2020
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8088
  context-path: /

