spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://8.210.38.19:3306/transaction_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    #username: root
    #password: gragon2020
    url: jdbc:mysql://127.0.0.1:3306/transaction_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8088
  context-path: /
file:
  wFileUrl: /data/file/
  lfileUrl: D:\\fish\\file\\

